sudo: required
services:
    - docker
language: generic

before_install:
    - docker build -t diegomateus/docker-react -f Dockerfile.dev .

Script:
    - docker run -e CI=true diegomateus/docker-react npm run test